### ISSUE TITLE
Getting started doubt

### ISSUE THREAD

**Issue by alejandrozf** [s-expressionists/Cleavir#14]
Hi guys, thank you so much for your work in this interesting project.

I just wanted some help in starting to use Cleavir.

I got it the the AST value using these steps on commit 04f1f75c:

CL-USER> 
; No values
CL-USER> (ql:quickload :cleavir-cst-to-ast)
To load "cleavir-cst-to-ast":
  Load 1 ASDF system:
    cleavir-cst-to-ast
; Loading "cleavir-cst-to-ast"

(:CLEAVIR-CST-TO-AST)
CL-USER> (defclass a-system () ())
#<STANDARD-CLASS COMMON-LISP-USER::A-SYSTEM>
CL-USER> (defclass environment () ())
#<STANDARD-CLASS COMMON-LISP-USER::ENVIRONMENT>
CL-USER> (defmethod cleavir-environment:optimize-info ((environment environment))
  (make-instance 'cleavir-environment:optimize-info
    :optimize '((speed 0) (compilation-speed 0) (space 0) (debug 3) (safety 3))
    :policy '()))
#<STANDARD-METHOD CLEAVIR-ENVIRONMENT:OPTIMIZE-INFO (ENVIRONMENT) {100474A6B3}>
CL-USER> (defmethod cleavir-environment:function-info
    (a-system (environment environment) function-name)
  (cond ((or (and (symbolp function-name)
                  (eq (symbol-package function-name)
                      (find-package 'cleavir-primop))
                  (not (eq function-name
                           'cleavir-primop:call-with-variable-bound)))
             (and (symbolp function-name)
                  (special-operator-p function-name)))
         (make-instance 'cleavir-environment:special-operator-info
           :name function-name))
        ((and (symbolp function-name)
              (eq (symbol-package function-name)
                  (find-package 'common-lisp))
              (not (null (macro-function function-name))))
         (make-instance 'cleavir-environment:global-macro-info
           :name function-name
           :expander (macro-function function-name)
           :compiler-macro nil))
        ((and (symbolp function-name)
              (eq (symbol-package function-name)
                  (find-package 'common-lisp))
              (typep (ignore-errors (fdefinition function-name)) 'function))
         (make-instance 'cleavir-environment:global-function-info
           :name function-name
           :dynamic-extent nil
           :ast nil
           :ignore nil
           :compiler-macro nil
           :inline nil
           :type t))
        (t nil)))
#<STANDARD-METHOD CLEAVIR-ENVIRONMENT:FUNCTION-INFO (T ENVIRONMENT T) {10048AC923}>
CL-USER> (defmethod cleavir-environment:variable-info (a-system (environment environment) symbol)
  (if (member symbol '(*special1* *special2*))
      (make-instance 'cleavir-environment:special-variable-info
        :global-p t
        :ignore nil
        :name symbol)
      nil))
#<STANDARD-METHOD CLEAVIR-ENVIRONMENT:VARIABLE-INFO (T ENVIRONMENT T) {10049B9F73}>
CL-USER> (defmethod cleavir-environment:eval (form (env1 environment) (env2 environment))
  (eval form))
#<STANDARD-METHOD CLEAVIR-ENVIRONMENT:EVAL (T ENVIRONMENT ENVIRONMENT) {1004A0AAD3}>
CL-USER> (cst:cst-from-expression (lambda (c) (/ c 4)))
#<CONCRETE-SYNTAX-TREE:ATOM-CST raw: #<FUNCTION (LAMBDA (C)) {5369164B}> {1004A200C3}>
CL-USER> (cleavir-cst-to-ast:cst-to-ast * (make-instance 'environment) 'a-system)
#<CLEAVIR-AST:CONSTANT-AST {1004C7ADB3}>
CL-USER> 

 but I couldn't find a way to compile  to BIR format
 I tried for example with
 CL-USER> (cleavir-ast-to-bir:compile-toplevel * 'a-system)
 but I got an error:
 There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLEAVIR-AST-TO-BIR:COMPILE-FUNCTION (2)>
when called with arguments
  (#<CLEAVIR-AST:CONSTANT-AST {1002712C93}> A-SYSTEM).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [RETRY] Retry SLY mREPL evaluation request.
 2: [*ABORT] Return to SLY's top level.
 3: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1004BC01F3}>)
 
 Could you give a hand to complete the compilation process?
 Thanks in advance

**Comment by alejandrozf** [comment]
Thanks Bike!

I tried with your suggestion but I got another errors related with some **environment:declarations** method

I think I will ask more in #sicl channel.

**Comment by Bike** [comment]
Sorry I missed on you on IRC. #sicl isn't always active so you might have to stick around for a little while. Here is what I said:

> i could try setting up an example later, but getting BIR by itself doesn't seem immediately useful
> the CLEAVIR-ENV:DECLARATIONS function just returns a list of symbols that have been proclaimed as declaration identifiers by the programmer. if you're doing a toy example, you can probably just define a method that always returns nil

**Comment by alejandrozf** [comment]
Thanks for all the answers, @Bike !
And also, the getting started added steps in the _Example_ folder are exactly what I was searching, it worked nice to me and it is helping me to understand the system
