### ISSUE TITLE
Where is cleavir-hir?

### ISSUE THREAD

**Issue by Ambrevar** [s-expressionists/Cleavir#21]
`cleavir-path-replication` depends on cleavir-hir, but I can't find this system.  Where is it hosted?

**Comment by Bike** [comment]
cleavir-path-replication was written for the previous version of cleavir, which had a different IR called HIR. the original project cleavir was forked from, SICL, has [the old Cleavir](https://github.com/robert-strandh/SICL/tree/master/Code/Cleavir) with HIR and path replication. But path replication is not applicable to the new IR, at least for the moment.

**Comment by Ambrevar** [comment]
OK, thanks for the details.
Maybe mention it in the doc?

**Comment by Bike** [comment]
i will probably just axe the subsystem; we can always get it back from the log or SICL if we need to. i'm only not doing so now because i've been very focused on a clasp project.
